language: node_js
node_js: 14
branches:
  only: master
install:
  - yarn
script:
  - yarn build
  - yarn test
deploy:
  api_key:
    secure: NZP+DkyVOlVE4vdw5Aw6XjyI7CCWNCoAPkm2K/2VOa3u7jvPBuyLY4Q1n4AtutseM1Z+iHdl7IuhY473FwSN6GeFb89LwDoTPrdQvOR7je0Bi1gEIIa92+j29kKWEMoKpKc3oBHGyXAmMtkymeCQ+l7M6J7spGUBPCbiJ/HlIdXsruxWQtfjnpkHzsAI5NdP7EmbZmipVmOazgPI4C3k/718sPBq44TQoaTOQdZKp+Ijj1VY26e5KyXhsqTYGdDuQv9qeI0o9m9FXn/K1MuyqdmYVgikhHiqVUlmBOzY4UCT75yVC12yLv5Nm55Y+bPJDL0ZqGjP/nIEvKDm5RRGOImYIEr/HRAA2LICCuiAnU8DINPUb7AaQdQkzHokk5o1X19e0RoxitwguYbi5v9KR4Lt7KsscI+CQ59A+ya1GwvJU/iqib/DBYNsAaS6leuRBNgiym2P0pP7uSy6TmyBSinZEPIzvYMoUjfgvRNlmJnvV/GRyOF/kBPWIM+eoObEBIyEoo7kdgGVuCqfvclGcA1UT89B3xdA7NQX93u9PeDvriRSaY9TlgJ4oQDBLDVHnbs+KmS9mm4d2AiW9DhBLC4Z3/+YSfB6CoGj4GBmg6LVqH4oxGP0Yfq6zfAe+U0cnpi6Vbc9LxdHjNsQIaHEoxZCvRRS9LwPJiLW9fCs2/A=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
